Numpy Provides its Own Data Structure for

Storing Data & Processing Data.

in Order to Leverage/Use builtin functions of Numpy we Must Use Numpy's Data Structure Only.

i.e.  ND Array

In [2]:
# first you must import numpy

import numpy as np

In [5]:
# here is a sample python list

distance_traveled = [  110 , 201, 102 , 150 , 128 ]

# objective: i wish to analyse this data using mathematics.
# 💡 I Must Convert the Above Python List into ND Array to be able to process data mathematically.

In [7]:
myArray = np.array(   distance_traveled  )

In [8]:
# np.array() converts python list into ND Array
# what is myArray ?
type(myArray)
# what does it contains ?
myArray
print('Total number of Bike Riders '  , myArray.size)
print('Longest Distance Traveled ', myArray.max())
print('Shortest Distance Traveled ', myArray.min())
print('Average Distance Traveled ', myArray.mean())
print('Standard Deviation ', myArray.std())

Total number of Bike Riders  5
Longest Distance Traveled  201
Shortest Distance Traveled  102
Average Distance Traveled  138.2
Standard Deviation  35.47618919782676

In [9]:
distance_traveled/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [10]:
myArray/2

array([ 55. , 100.5,  51. ,  75. ,  64. ])

Efficiency Test ( Python vs Numpy )
1. Memory Occupancy Test

In [11]:
# python test
import sys

print(sys.getsizeof(5),' bytes')

28  bytes

In [12]:
# numpy test

print( myArray.itemsize, ' bytes')

4  bytes

Performance test 
objective to add 1 million number using python vs numpy,one taking less time to complete opertion will be the winner

In [13]:
import time
import numpy as np

SIZE = 1000000

A1 = range( SIZE )
A2 = range( SIZE )

L1 = np.arange( SIZE )
L2 = np.arange( SIZE )

# Python Test
start = time.time()
result= [x+y for x,y in zip(A1,A2)]
stop = time.time()

print('🐍 Python took ', (stop-start) * 1000 , ' ms')

# Numpy Test

start = time.time()
result = L1 + L2
stop = time.time()

print('👨‍🔬 Numpy Took ' , (stop-start) * 1000,' ms')

🐍 Python took  297.82581329345703  ms
👨‍🔬 Numpy Took  15.0146484375  ms

Working with 2D Array

You are Provided with Weather Information Where,

Columns Represent Year i.e. 1990 , 1991 , 1992

Rows Represent Months i.e.  Jan / Feb  / Mar / Apr

In [14]:
weather_info = [
    [ 10 , 12, 14],
    [ 8  , 11, 13],
    [ 15 , 18, 16],
    [ 22 , 19, 17 ]
]

In [15]:
w_arr = np.array ( weather_info )

In [16]:
w_arr

array([[10, 12, 14],
       [ 8, 11, 13],
       [15, 18, 16],
       [22, 19, 17]])

In [17]:
print('Count of Elements ' , w_arr.size)
print('DataType of Elements ' , w_arr.dtype)
print('Size of Each Element ( bytes )' , w_arr.itemsize)
print('Memory Occupied by Whole Array (bytes)' , w_arr.nbytes)
print('Shape of Matrix ', w_arr.shape)
print('Number of Dimensions',w_arr.ndim)

Count of Elements  12
DataType of Elements  int32
Size of Each Element ( bytes ) 4
Memory Occupied by Whole Array (bytes) 48
Shape of Matrix  (4, 3)
Number of Dimensions 2

In [18]:
w_arr[3,2]

17

In [22]:
w_arr[2,0]

15

using .flatten() function to corvert 2D array into 1D array

In [23]:
flat_array = w_arr.flatten()

Filtering Elements in ND Array

In [24]:
flat_array

array([10, 12, 14,  8, 11, 13, 15, 18, 16, 22, 19, 17])

In [25]:
flat_array<15

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False])

In [26]:
flat_array [flat_array<15]

array([10, 12, 14,  8, 11, 13])

In [27]:
flat_array [flat_array % 2 ==0]

array([10, 12, 14,  8, 18, 16, 22])

In [28]:
flat_array [flat_array % 2 ==1]

array([11, 13, 15, 19, 17])

In [29]:
flat_array [ ~(flat_array % 2 ==0)]

array([11, 13, 15, 19, 17])

In [31]:
flat_array [flat_array % 2 !=0]

array([11, 13, 15, 19, 17])

In [32]:
flat_array [(flat_array>=7) & (flat_array <=12)]

array([10, 12,  8, 11])

In [33]:
flat_array [(flat_array % 3==0) | (flat_array % 5==0)]

array([10, 12, 15, 18])

In [36]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [37]:
x+y

array([[ 6,  8],
       [10, 12]])

In [38]:
x*y

array([[ 5, 12],
       [21, 32]])

In [40]:
y-x

array([[4, 4],
       [4, 4]])

In [41]:
y/x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [42]:
y**x

array([[   5,   36],
       [ 343, 4096]])

In [43]:
#hstack
np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [45]:
#vstack
np.vstack((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Suppose a Fruit Seller Sold 20 Mangoes and 10 Oranges in one Day for a total of 350 . the next day he sold 17 mangoes and 22 oranges for 500. if the price of fruit remains unchanged on both days , what was the price of one mango 🥭 and one orange 🍊

In [46]:
#20x + 10y =350
#17x + 22y=500

In [47]:
coeff=np.array([[20,10],[17,22]])

In [48]:
const=np.array([350,500])

In [49]:
result=np.linalg.solve(coeff,const)
print(result)

[10. 15.]

x +  2y + 3z =  32
2x + 3y + z  =  24
3x + y + 2z  =  22

In [50]:
coeff1=np.array([[1,2,3],[2,3,1],[3,1,2]])

In [54]:
const1=np.array([32,24,22])

In [53]:
result1=np.linalg.solve(coeff1,const1)
print(result1)

[1. 5. 7.]

In [1]:
# import pandas
import pandas as pd

priceList=[120,410,390,220,320]

mySeries=pd.Series(priceList)

In [56]:
print(type(mySeries))

<class 'pandas.core.series.Series'>

In [57]:
print(mySeries)

0    120
1    410
2    390
3    220
4    320
dtype: int64

Fact : Pandas Data Structure i.e. Series and DataFrame both Use ND Array Internally to Store and Process Data.
it simply means features of ND Array i.e. Vectorisation , memory efficiency , performance and Only ND Array Functions (Excluding Numpy Functions) are Available in pandas

In [58]:
mySeries.values.sum()

1460

In [59]:
mySeries.values.mean()

292.0

Creating Dataframe

In [64]:
nba=pd.read_csv('nba.csv')

In [65]:
print(type(nba))

<class 'pandas.core.frame.DataFrame'>

In [67]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [69]:
nba.shape

(458, 9)

In [72]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [73]:
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [75]:
nba.columns.tolist()

['Name',
 'Team',
 'Number',
 'Position',
 'Age',
 'Height',
 'Weight',
 'College',
 'Salary']

In [79]:
#describe() this return statiscical facts about all numerical columns present in Data.
nba.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [77]:
#info() : this function returns detailed summary of the dataframe

nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [80]:
nba.isna().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [81]:
#.head() first 5 rows
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [84]:
#.tail() last 5 rows
nba.tail(5)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
nba.Name

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [86]:
nba['Name']

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

assuming if a column is having a space in its label eg. 'my college'

nba.my college ❌

nba['my college'] ✅

In [87]:
#select muliple column from the dataframe
mycols=['Name','College','Salary']
nba[mycols].head(3)

            Name            College     Salary
0  Avery Bradley              Texas  7730337.0
1    Jae Crowder          Marquette  6796117.0
2   John Holland  Boston University        NaN

In [88]:
nba[['Name','College','Salary']].head(3)

            Name            College     Salary
0  Avery Bradley              Texas  7730337.0
1    Jae Crowder          Marquette  6796117.0
2   John Holland  Boston University        NaN

In [89]:
#filtering record 
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [91]:
texasplayer= nba.College =='Texas'
nba [ texasplayer]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0
289,Jordan Hamilton,New Orleans Pelicans,25.0,SG,25.0,6-7,220.0,Texas,1015421.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0

In [94]:
nba [ nba.College=='Texas']

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0
289,Jordan Hamilton,New Orleans Pelicans,25.0,SG,25.0,6-7,220.0,Texas,1015421.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0

In [95]:
nba[nba.Team=='Boston Celtics']

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0

In [98]:
#multiple condtion
nba[(nba.College=='Texas') & (nba.Position=='PG')]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0

In [99]:
c1= nba.College=='Texas'
c2= nba.Position=='PG'
nba[ c1 & c2]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0

In [104]:
nba.tail(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
nba[(nba.Team=='Toronto Raptors') & (nba.Age<24)]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
61,Bismack Biyombo,Toronto Raptors,8.0,C,23.0,6-9,245.0,NaN,2814000.0
62,Bruno Caboclo,Toronto Raptors,20.0,SF,20.0,6-9,205.0,NaN,1524000.0
68,Lucas Nogueira,Toronto Raptors,92.0,C,23.0,7-0,220.0,NaN,1842000.0
70,Norman Powell,Toronto Raptors,24.0,SG,23.0,6-4,215.0,UCLA,650000.0

In [107]:
#salary of the player is null
nba[(nba.Salary.isnull()) ]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,NaN
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,NaN
264,Jordan Farmar,Memphis Grizzlies,4.0,PG,29.0,6-2,180.0,UCLA,NaN
269,Ray McCallum,Memphis Grizzlies,5.0,PG,24.0,6-3,190.0,Detroit,NaN
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,NaN
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,NaN
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,NaN,NaN
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,NaN
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
nba[nba.Salary.isnull()].shape

(12, 9)

In [109]:
nba[nba.Salary.notnull()].shape

(446, 9)

In [110]:
#sorting
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [112]:
nba.sort_values(by='Age',ascending=True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
226,Rashad Vaughn,Milwaukee Bucks,20.0,SG,19.0,6-6,202.0,UNLV,1733040.0
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0
40,Kristaps Porzingis,New York Knicks,6.0,PF,20.0,7-3,240.0,NaN,4131720.0
401,Tyus Jones,Minnesota Timberwolves,1.0,PG,20.0,6-2,195.0,Duke,1282080.0
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
...,...,...,...,...,...,...,...,...,...
102,Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,NaN,947726.0
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000.0
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,NaN,8500000.0
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [120]:
nba[(nba.Team=='Memphis Grizzlies') & (nba.Position=='PG')].sort_values('Salary',ascending=False).head(1)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
262,Mike Conley,Memphis Grizzlies,11.0,PG,28.0,6-1,175.0,Ohio State,9588426.0

In [4]:
arr = np.array([1, 2, 3, 4, 5])
arr = np.append(arr = arr, values = 6)
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])
np.concatenate([arr1, arr2, arr3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr = np.array(['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy'])

In [8]:
np.reshape(a = arr, newshape = (2, 3))

array([['Ashok', 'Ravi', 'Kumar'],
       ['Shiela', 'P.', 'Reddy']], dtype='<U6')

In [9]:
np.reshape(arr, (1, 1, 6))

array([[['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy']]], dtype='<U6')

In [10]:
mat = np.array([['Apple', 'Bread', 'Cheese'], ['Rs. 120', 'Rs. 20', 'Rs. 150']])

In [11]:
mat.transpose()

array([['Apple', 'Rs. 120'],
       ['Bread', 'Rs. 20'],
       ['Cheese', 'Rs. 150']], dtype='<U7')

In [12]:
mat.ravel()

array(['Apple', 'Bread', 'Cheese', 'Rs. 120', 'Rs. 20', 'Rs. 150'],
      dtype='<U7')

In [13]:
mat.flatten()

array(['Apple', 'Bread', 'Cheese', 'Rs. 120', 'Rs. 20', 'Rs. 150'],
      dtype='<U7')

In [3]:
named_series = pd.Series(data = ['Ashok', 'Kumar', 18, 183], index = ['Forename', 'Surname', 'Age', 'Height'], name = 'Student Info')

named_series

Forename    Ashok
Surname     Kumar
Age            18
Height        183
Name: Student Info, dtype: object

In [4]:
named_series.dtype

dtype('O')

In [5]:
named_series.values

array(['Ashok', 'Kumar', 18, 183], dtype=object)

In [6]:
named_series.name

'Student Info'

In [7]:
my_series = pd.Series({'A': 1, 'B': 2, 'C': 3, 'D': 4})
my_series

A    1
B    2
C    3
D    4
dtype: int64

In [ ]:
my_series = pd.Series(data = [32, 33, 30, 29, 36], index = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], name = 'Peak Temperature')

In [ ]:
my_series.iloc[0]

In [ ]:
my_series['Tue']

In [ ]:
my_series.iloc[1:3]

In [ ]:
my_series.loc['Tue':'Thu']

In [ ]:
sorted_series = my_series.sort_values()

In [ ]:
my_series.loc[my_series.isin([28, 29, 30])]

In [ ]:
phone_steps = pd.Series(data = [6000, 7400, 6750, 8000, 5500], index = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], name = 'Phone')

smartwatch_steps = pd.Series(data = [5500, 4750, 6250], index = ['Mon', 'Wed', 'Fri'], name = 'Smart Watch')

In [ ]:
phone_steps + smartwatch_steps

In [ ]:
phone_steps.add(smartwatch_steps, fill_value = 0)

#Pandas String and datetime function

In [4]:
import pandas as pd
import numpy as np

In [2]:
companies = pd.Series(['Meta ', 'Ama!on ', '#Apple', '#Netflix', 'Google ', 'CORRUPT'])

In [3]:
companies.str.contains('!')

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [4]:
dates = pd.Series(['2024-01-01', '2024-02-15', '2024-03-30'])
datetime_series = pd.to_datetime(dates)

In [5]:
datetime_series.dt.year

0    2024
1    2024
2    2024
dtype: int32

In [ ]:
df_empty = pd.DataFrame()

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Chandni', 'Dawood'],
    'Age': [25, 30, 18, 22],
    'City': ['Mumbai', 'Kolkata', 'Delhi', 'Bengaluru']
}

df1 = pd.DataFrame(data = data)

In [ ]:
df1.dtypes

In [ ]:
df1.ndim

In [ ]:
df1.index

In [ ]:
df1.columns

In [5]:
data1 = {
    'Name': ['Ashok', 'Bob', 'Chandni', 'Dawood', 'Esha'],
    'Age': [25, 30, 18, 22, 30],
    'City': ['Mumbai', 'Kolkata', 'Delhi', 'Bengaluru', 'Agra'],
    'Income June': [30000, 40000, 50000, 60000, np.nan],
    'Income July': [30500, 40000, 50000, np.nan, 70000]
}

df1 = pd.DataFrame(data1)

In [6]:
df1['Tax on Income'] = 0.1 * (df1['Income June'] + df1['Income July'])

In [7]:
df1['Tax on Income'] = 0.1 * df1['Income June'].add(df1['Income July'], fill_value = 0)

In [8]:
df1['Income June'].sum()

180000.0

In [9]:
df1['Income June'].mean()

45000.0

In [10]:
df1['Age'].sort_values()

2    18
3    22
0    25
1    30
4    30
Name: Age, dtype: int64

In [13]:
df1['Tax in Dollars'] = df1['Tax on Income'].apply(lambda x: x / 84)

## Merge and concatination
df_volume = pd.read_csv('GOOGL_volume.csv')
df_prices = pd.read_csv('GOOGL_prices.csv')


df_inner_join = pd.merge(df_volume, df_prices, on = 'Date', how = 'inner')
df_outer_join = pd.merge(df_volume, df_prices, on = 'Date', how = 'outer')
df_left_join = pd.merge(df_volume, df_prices, on = 'Date', how = 'left')
df_right_join = pd.merge(df_volume, df_prices, on = 'Date', how = 'right')
df_cross_join = pd.merge(df_volume, df_prices, how = 'cross')
df_concat_rows = pd.concat([df_volume, df_prices], axis = 0)
df_concat_cols = pd.concat([df_volume, df_prices], axis = 1)

In [14]:
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance', 'Finance', 'Finance'],
    'Product': ['ChatBot', 'Autoflagger', 'ChatBot', 'Autoflagger', 'ChatBot', 'Autoflagger', 'Autoflagger'],
    'Employee': ['Ashok', 'Bob', 'Chandni', 'Dawood', 'Esha', 'Falak', 'Girish'],
    'Salary': [50000, 55000, 60000, 65000, 70000, 72000, 80000],
    'Bonus': [5000, 6000, 7000, 8000, 9000, 9500, 10000]
}

df = pd.DataFrame(data)

In [19]:
department_sum = df.groupby('Department').sum()
department_sum

                                  Product         Employee  Salary  Bonus
Department
Finance     ChatBotAutoflaggerAutoflagger  EshaFalakGirish  222000  28500
HR                     ChatBotAutoflagger         AshokBob  105000  11000
IT                     ChatBotAutoflagger    ChandniDawood  125000  15000

In [20]:
department_sum = df.groupby('Department').sum()
department_sum

                                  Product         Employee  Salary  Bonus
Department
Finance     ChatBotAutoflaggerAutoflagger  EshaFalakGirish  222000  28500
HR                     ChatBotAutoflagger         AshokBob  105000  11000
IT                     ChatBotAutoflagger    ChandniDawood  125000  15000

In [21]:
department_count = df.groupby('Department').count()
department_count

            Product  Employee  Salary  Bonus
Department
Finance           3         3       3      3
HR                2         2       2      2
IT                2         2       2      2

In [22]:
df_pivoted = df.pivot(index = 'Department', columns = 'Employee', values = 'Salary')
df_pivoted

Employee      Ashok      Bob  Chandni   Dawood     Esha    Falak   Girish
Department
Finance         NaN      NaN      NaN      NaN  70000.0  72000.0  80000.0
HR          50000.0  55000.0      NaN      NaN      NaN      NaN      NaN
IT              NaN      NaN  60000.0  65000.0      NaN      NaN      NaN